version: "3.8"

# The services
services:
# MariaDB
    mariadb:
        container_name: mariadb
        build: ./srcs/requirements/mariadb
        expose:
            - "3306"
        volumes:
            - mariadb_data:/var/lib/mysql
        env_file:
            - .env
        networks:
            - inception
        restart: always
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 10
# Nginx
    nginx:
        container_name: nginx
        build: ./srcs/requirements/nginx 
        expose:
            - "9000"
        ports:
            - "443:443"
        depends_on:
            - wordpress
        volumes:
            - wordpress-file:/var/www/wordpress
            - ./srcs/requirements/nginx/tools/ssl:/etc/nginx/ssl
        networks:
            - inception
        restart: always
# Wordpress
    wordpress:
        container_name: wordpress
        build: ./srcs/requirements/wordpress
        expose:
            - "9000"
            - "3306"
        depends_on:
            mariadb:
                condition: service_healthy
        volumes:
            - wordpress-file:/var/www/wordpress
        env_file:
            - .env
        networks:
            - inception
        restart: always 

# The volumes   
volumes:
    mariadb_data:
        name: mariadb
        driver: local
        driver_opts:
            device: /home/tzi-qi/data/mariadb
            o: bind
            type: none
    wordpress-file:
        name: wordpress
        driver: local
        driver_opts:
            device: /home/tzi-qi/data/wordpress
            o: bind
            type: none

# The networks
networks:
    inception:
        name: inception 